# Generated by Django 4.0.4 on 2022-04-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('lens_mount', models.CharField(max_length=50)),
                ('sensor_size', models.CharField(max_length=50)),
                ('sensor_mp', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
