# Generated by Django 4.0.4 on 2022-04-25 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('lens_type', models.CharField(max_length=30)),
                ('focal_length', models.CharField(max_length=30)),
                ('image_stab', models.BooleanField()),
                ('mount', models.CharField(max_length=30)),
                ('max_aperature', models.CharField(max_length=10)),
                ('min_aperature', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='images/lenses/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images/cameras/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
