# Generated by Django 4.0.4 on 2022-04-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_lens_camera_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='image',
        ),
    ]
