# Generated by Django 4.0.4 on 2022-04-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_camera_image_remove_lens_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lens',
            old_name='max_aperature',
            new_name='max_aperture',
        ),
        migrations.RenameField(
            model_name='lens',
            old_name='min_aperature',
            new_name='min_aperture',
        ),
    ]
