# Generated by Django 4.0.4 on 2022-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_camera_make_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='make',
            field=models.CharField(choices=[('AGF', 'Agfa'), ('CAN', 'Canon'), ('CAS', 'Casio'), ('CON', 'Contax'), ('DXO', 'DxO Labs'), ('FUJ', 'Fujifilm'), ('HAS', 'Hasselblad'), ('KOD', 'Kodak'), ('MIN', 'Minolta'), ('KYO', 'Kyocera'), ('LEI', 'Leica'), ('NIK', 'Nikon'), ('OLY', 'Olympus'), ('PAN', 'Panasonic'), ('PEN', 'Pentax'), ('RIC', 'Ricoh'), ('SAM', 'Samsung'), ('SIG', 'Sigma'), ('SON', 'Sony'), ('ZEI', 'Zeiss')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lens',
            name='image_stab',
            field=models.BooleanField(verbose_name='Image Stabilized'),
        ),
    ]
