# Generated by Django 4.0.4 on 2022-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_accessory_make_alter_accessory_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
