# Generated by Django 4.0.4 on 2022-04-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_kit_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='accessories',
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
