# Generated by Django 4.0.4 on 2022-04-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_kit_accessories_delete_accessory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='lenses',
            new_name='lens',
        ),
    ]
