# Generated by Django 4.0.4 on 2022-04-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_lenses_kit_lens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='lens',
            new_name='lenses',
        ),
    ]
