# Generated by Django 4.0.4 on 2022-04-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_lens_kit_lenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name_plural': 'lenses'},
        ),
    ]
